### ISSUE TITLE
Add README translations

### ISSUE THREAD

**Issue by kyu08** [kyu08/fzf-make#106]
- Add translation which has file name like `doc/README-ja.md`.
- Add the link in `README.md` in the same format as [sharkdp/bat](https://github.com/sharkdp/bat).

**Comment by ColtonShiu** [comment]
@kyu08 I can add a translation, may I get assigned to this task?

**Comment by kyu08** [comment]
@ColtonShiu 
I appreciate your offer!
I will not assign this issue to anyone in particular as I am happy to have multiple languages translated.
I want to reassure you that the PR for the language you are translating into will take priority over yours.
If you have any concerns, please don't hesitate to ask.

**Comment by wrth1337** [comment]
Hi @kyu08 
I translated the README into German and added the linking. #107

**Comment by Ganeshkharde1** [comment]
hey I can add it in multiple languages, please assign it to me

**Comment by kyu08** [comment]
@ColtonShiu 
I waited a few days and got no response, so I will review the PR currently submitted (https://github.com/kyu08/fzf-make/pull/107) and merge it if there are no problems.
If you are willing to translate anything other than German, I'm open to your PRs.
If you just tell me which language you are trying to translate into before submitting your PR, I will give your PR priority over others.

**Comment by kyu08** [comment]
@Ganeshkharde1 
I will accept PR as long as it is in a language other than the one @ColtonShiu  is trying to translate.
Can you tell me the language you are trying to translate into?(If you don't hear back from @ColtonShiu for a few days, you can translate the language of your choice.)

Also, as I mentioned in [this comment](https://github.com/kyu08/fzf-make/issues/106#issuecomment-1777559305), I'm not going to assign this issue to anyone in particular because  I'd prefer to see additional translations into multiple languages.
Thanks.
