### ISSUE TITLE
Add crates.io badge to README

### ISSUE THREAD

**Issue by kyu08** [kyu08/fzf-make#108]
## TODO
- [ ] Add badge to readme
  - [ ] en
  - [ ] german

Format might be following:
```html
  ![crates.io](https://img.shields.io/crates/v/fzf-make?style=flatflat-square)
```

that shows like this.

![crates.io](https://img.shields.io/crates/v/fzf-make?style=flatflat-square)

**Comment by khanh130202** [comment]
can i do this issue ???

**Comment by kyu08** [comment]
@khanh130202 
Yes please!
