### ISSUE TITLE
Typo in the release page

### ISSUE THREAD

**Issue by orhun** [kyu08/fzf-make#118]
![image](https://github.com/kyu08/fzf-make/assets/24392180/d831acc7-8769-4a95-9891-122be4dfe1a8)

`rartatui` -> `ratatui` 🐻

**Comment by kyu08** [comment]
@orhun 
Fixed!
Thank you for letting me know that mistake!

**Comment by orhun** [comment]
No worries, new release rocks btw 🚀

**Comment by kyu08** [comment]
Thanks to ratatui, I can develop smoothly! Thank you for contribution to ratatui!
Also, your work always motivates me! Thanks again!

If you notice anything, I'd be glad to hear your feedback for fzf-make.

**Comment by orhun** [comment]
Sure thing! Feel free to add `fzf-make` to https://github.com/ratatui-org/ratatui/wiki/Apps-using-Ratatui

**Comment by kyu08** [comment]
Oh...! I did not know that page! Thanks! I added.
https://github.com/ratatui-org/ratatui/wiki/Apps-Using-Ratatui#-productivity-and-utilities
