### ISSUE TITLE
Sometimes preview window blinks

### ISSUE THREAD

**Issue by kyu08** [kyu08/fzf-make#124]
This occurs randomly.

https://github.com/kyu08/fzf-make/assets/49891479/ece4f008-9f15-40c3-990d-631883c6ed47

**Comment by kyu08** [comment]
This was not reproduced in the release version. (May be caused by some differences between binary generated by `cargo run` and `cargo build --release`)

**Comment by Sigmanificient** [comment]
It seems to only happens when mouse is moving 
![Peek 2024-03-17 14-36](https://github.com/kyu08/fzf-make/assets/53050011/18c215b0-ab0d-4441-a31c-76830dc523cc)
