### ISSUE TITLE
`panic: Any { .. }` when including deps files on a Makefile

### ISSUE THREAD

**Issue by Sigmanificient** [kyu08/fzf-make#150]
Not sure how to help with this issue but running fzf-make causes a panic:

```
nix run github:kyu08/fzf-make
panic: Any { .. }
```

**Comment by kyu08** [comment]
@Sigmanificient 
Thank you for your report!
I have some questions.

1. This occurs every time you launch fzf-make or only sometimes?
2. What is the version you use?
3. Does `fzf-make --version` work fine?

**Comment by Sigmanificient** [comment]
Hi, here is some details that might help you:

Asking for version & help works fine
```
fzf-make --version
v0.11.0
```

Running on a directory without Makefile opens an empty GUI
![image](https://github.com/kyu08/fzf-make/assets/53050011/9921d9ea-9068-446d-8161-47716222a077)
and quitting it causes `panic: Any { .. }`

Running with `RUST_BACKTRACE=1` does not provide further information.

Running on a directory with a Makefile causes instant crash.
It seems to work when using this dummy Makefile:
```
a:
     echo "test"
.PHONY: a
```
Although still panicking on exit.

Here is my project Makefile:
https://gist.github.com/Sigmanificient/a7e54f6152ece75430a8f8846b06d9d6

**Comment by Sigmanificient** [comment]
It seems that removing the 2 last lines make it works again
```
-include $(DEP)
-include $(DEP_DEBUG)
```

**Comment by kyu08** [comment]
Ahh! I see!
Now, fzf-make can not interpret include file path that includes variable like `-include $(DEP)`.

I will fix this problem. Thank you for your input and take time for this!

**Comment by Sigmanificient** [comment]
> Ahh! I see! Now, fzf-make can not interpret include file path that includes variable like `-include $(DEP)`.
> 
> I will fix this problem. Thank you for your input and take time for this!

Those files might not exist before the run by the user, as for the `-` before the `include` keyword.
In the previous scenario, they existed but beware to consider this too.

**Comment by kyu08** [comment]
As a short time measure, I'll fix this to ignore a makefile that can not be found and `include`-directive with variable.
After that, I will think what is better solution.

**Comment by Sigmanificient** [comment]
If you want to challenge yourself, feel free to check out the Makefile featured in [this project](https://github.com/Sigmanificient/LeetCode_C).

It imports a list of sub-makefiles from a variable with make preprocessor and eval along a global helper makefile,
but use a condition to exclude the global helper makefile to import in sub-makefiles

**Comment by Sigmanificient** [comment]
[0.11.0 -> 0.12.0](https://github.com/NixOS/nixpkgs/pull/274780)

**Comment by kyu08** [comment]
Thanks!
