### ISSUE TITLE
[documentation] How to have fzf-make imported into `homebrew/core`

### ISSUE THREAD

**Issue by kyu08** [kyu08/fzf-make#195]
https://docs.brew.sh/Acceptable-Formulae#niche-or-self-submitted-stuff

In the future, when fzf-make is famous, I will submit PR to brew. 😇

> The software in question must:
> 
> be maintained (i.e. the last release wasn’t ages ago, it works without patching on all Homebrew-supported OS versions and has no outstanding, unpatched security vulnerabilities)
> be stable (e.g. not declared “unstable” or “beta” by upstream)
> be known
> be used
> have a homepage
> We will reject formulae that seem too obscure, partly because they won’t get maintained and partly because we have to draw the line somewhere.
> 
> We frown on authors submitting their own work unless it is very popular.
> 
> Don’t forget Homebrew is all Git underneath! Maintain your own tap if you have to!
> 
> There may be exceptions to these rules in the main repository; we may include things that don’t meet these criteria or reject things that do. Please trust that we need to use our discretion based on our experience running a package manager.

## Ref
- https://github.com/Homebrew/homebrew-core/pull/77138

**Comment by kyu08** [comment]
At first, if we got 50 stars, I will submit PR to https://github.com/rust-unofficial/awesome-rust.

> In order to make this objective, the entry needs to either have at least 50 stars on Github, 2000 downloads on crates.io, or an equivalent level of other popularity metrics (which should be specified in the PR). 

https://github.com/rust-unofficial/awesome-rust/blob/main/CONTRIBUTING.md

**Comment by kyu08** [comment]
Finally, fzf-make was added to homebrew-core. 🎉

https://github.com/Homebrew/homebrew-core/pull/200454

**Comment by p-linnane** [comment]
In addition to maintaining Homebrew, I search for awesome software that we don't currently ship so that I can add it for distribution. Was happy to find `fzf-make` and ship it! おめでとう〜！
