### ISSUE TITLE
fix(ui): use trishume/syntect to highligh files instead of using bat with tui-term

### ISSUE THREAD

**Issue by kyu08** [kyu08/fzf-make#234]
## What this issue proposing
- Use https://github.com/trishume/syntect instead of running `bat` command using tui-term.
- https://github.com/chanq-io/syntect-tui seems useful for ratatui and syntect.

## Motivation
- If this is fit for fzf-make, these will be resolved.
    - https://github.com/kyu08/fzf-make/issues/124
    - https://github.com/kyu08/fzf-make/issues/144
    - https://github.com/kyu08/fzf-make/issues/49
- Now, the cursor moves slowly when hold to press arrow key. It may be solved by this change.

## Ref
Since https://github.com/dustinblackman/oatmeal utilizes trishume/syntect, it might serve as a reference.
https://github.com/dustinblackman/oatmeal/blob/858207ed5bce233aa9ce55a60fb958fc965b6c75/src/domain/services/bubble.rs#L83

**Comment by Sigmanificient** [comment]
What about tree-sitter?

**Comment by kyu08** [comment]
@Sigmanificient 
Thanks for the idea.
This crate may be helpful. https://crates.io/crates/tree-sitter-highlight
I'll try it when I work on this issue.
