### ISSUE TITLE
Subscripts detected as runnable targets

### ISSUE THREAD

**Issue by Sigmanificient** [kyu08/fzf-make#236]
Hi, I tried to run `fzf-make` on the glibc repos to get a better overview of the monster that is the *[Master Makefile for the GNU C library](https://sourceware.org/git/?p=glibc.git;a=blob;f=Makefile;h=7052b46df83ec25d70160dce4ec6c33086c72de6;hb=refs/heads/master)* (yes this boi is 23k lines long). I was surprised that it even opened the preview window under 2s, (still very laggy but hey, that's a real stress test, to say the least)!

![image](https://github.com/kyu08/fzf-make/assets/53050011/d8cd2c8c-0087-4e43-8d45-c4689f498827)

Here is a minimal example to reproduce this issue:
```mk
.PHONY: real_rule
real_rule:
	echo "good"

define my_script
#!/bin/bash

echo "this is a trap: not good"
endef
```

Skipping defines blocks would help to filter these lines easily
![image](https://github.com/kyu08/fzf-make/assets/53050011/12469c14-eab1-4297-96b3-b96096c3c366)

**Comment by kyu08** [comment]
@Sigmanificient 

Thank you for letting me know the issue and take time to report!

For now, the extraction of the target is done by reading the contents of the Makefile line by line, but it seems that it can be avoided by excluding irrelevant lines such as `defines` blocks before extracting the target.

Thank you for always reporting the issue in detail!
