### ISSUE TITLE
Make sure it works on linux

### ISSUE THREAD

**Issue by kyu08** [kyu08/fzf-make#52]
It's fine to test using linux container image on Docker...? (I don't have linux machine)

TODO: Update my homebrew repo if needed. (for installation on linux)

**Comment by Sigmanificient** [comment]
> It's fine to test using linux container image on Docker...? (I don't have linux machine)
> 
It works perfectly on linux! I added a	flake.nix for building it within nix! (reproducible on any distro)
[Check it out!](#54)

**Comment by kyu08** [comment]
This issue could be closed, because a few developers including you made sure it works on Linux.

@Sigmanificient 
Thanks for your comment.
