### ISSUE TITLE
Run `cargo fmt`, `cargo clippy` on CI

### ISSUE THREAD

**Issue by kyu08** [kyu08/fzf-make#74]
# Maintainer TODO
> - Be ready to review pull/merge requests, accepting those that are valid by merging them, leaving an overall approving review, or by adding the “hacktoberfest-accepted” label.
> - Reject any spammy requests you receive by labeling them as “spam,” and any other invalid contributions by closing them or labeling them as “invalid.”

https://hacktoberfest.com/participation/#maintainers

**Comment by engineerakki** [comment]
I can pick this up:

https://github.com/kyu08/fzf-make/pull/98
